database:
	host: localhost
	port: 27017
	database: aurbs
	# Only define this, if db requires auth:
	#user: aurbs
	#pass: dbpass

public_repo:
	name: unixfox
	# http_url: Alternative public url
	# otherwise /<name> will be used and served
	http_url: https://aur.unixfox.eu
	rsync:
		# url: RSYNC target url to sync to after building
		# pass: RSYNC password
		#url: aurbs@domain.net::aurbs
		#pass: secretrsyncpwd

architectures:
	- x86_64

aurpkgs:
